import { PrismaClient, AchievementCategory, ExamType } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedAchievements(schoolId: string) {
  console.log('🏆 Seeding achievements...');

  const achievements = [
    // ==================== STREAK ACHIEVEMENTS (Düzenlilik) ====================
    {
      name: '1 Hafta Düzenli',
      description: '1 hafta boyunca tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'STREAK_1W',
      requirement: { weeks: 1 },
      iconName: 'flame',
      colorScheme: 'orange',
      points: 10,
    },
    {
      name: '2 Hafta Düzenli',
      description: '2 hafta üst üste tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'STREAK_2W',
      requirement: { weeks: 2 },
      iconName: 'flame',
      colorScheme: 'orange',
      points: 25,
    },
    {
      name: '3 Hafta Düzenli',
      description: '3 hafta üst üste tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'STREAK_3W',
      requirement: { weeks: 3 },
      iconName: 'flame',
      colorScheme: 'orange',
      points: 50,
    },
    {
      name: '1 Ay Düzenli',
      description: '4 hafta üst üste tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'STREAK_4W',
      requirement: { weeks: 4 },
      iconName: 'flame',
      colorScheme: 'orange',
      points: 75,
    },
    {
      name: '5 Hafta Düzenli',
      description: '5 hafta üst üste tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'STREAK_5W',
      requirement: { weeks: 5 },
      iconName: 'flame',
      colorScheme: 'red',
      points: 100,
    },
    {
      name: '8 Hafta Düzenli',
      description: '8 hafta üst üste tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'STREAK_8W',
      requirement: { weeks: 8 },
      iconName: 'flame',
      colorScheme: 'red',
      points: 150,
    },
    {
      name: '3 Ay Düzenli',
      description: '12 hafta üst üste tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'STREAK_12W',
      requirement: { weeks: 12 },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 200,
    },

    // ==================== CLASS RANKINGS ====================
    {
      name: 'Sınıfın Şampiyonu',
      description: 'Denemede sınıfında 1. oldun',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_CLASS_1',
      requirement: { rank: 1, scope: 'CLASS' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 50,
    },
    {
      name: 'Sınıfta İlk 3',
      description: 'Denemede sınıfında ilk 3\'e girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_CLASS_3',
      requirement: { rank: 3, scope: 'CLASS' },
      iconName: 'trophy',
      colorScheme: 'blue',
      points: 30,
    },
    {
      name: 'Sınıfta İlk 5',
      description: 'Denemede sınıfında ilk 5\'e girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_CLASS_5',
      requirement: { rank: 5, scope: 'CLASS' },
      iconName: 'award',
      colorScheme: 'blue',
      points: 20,
    },
    {
      name: 'Sınıfta İlk 10',
      description: 'Denemede sınıfında ilk 10\'a girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_CLASS_10',
      requirement: { rank: 10, scope: 'CLASS' },
      iconName: 'medal',
      colorScheme: 'blue',
      points: 10,
    },

    // ==================== LGS SCHOOL RANKINGS ====================
    {
      name: 'Okulda Şampiyon',
      description: 'LGS denemesinde okulunda 1. oldun',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_SCHOOL_1_LGS',
      requirement: { rank: 1, scope: 'SCHOOL' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 100,
      examType: ExamType.LGS,
    },
    {
      name: 'Okulda İlk 3',
      description: 'LGS denemesinde okulunda ilk 3\'e girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_SCHOOL_3_LGS',
      requirement: { rank: 3, scope: 'SCHOOL' },
      iconName: 'trophy',
      colorScheme: 'blue',
      points: 50,
      examType: ExamType.LGS,
    },
    {
      name: 'Okulda İlk 5',
      description: 'LGS denemesinde okulunda ilk 5\'e girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_SCHOOL_5_LGS',
      requirement: { rank: 5, scope: 'SCHOOL' },
      iconName: 'award',
      colorScheme: 'blue',
      points: 30,
      examType: ExamType.LGS,
    },
    {
      name: 'Okulda İlk 10',
      description: 'LGS denemesinde okulunda ilk 10\'a girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_SCHOOL_10_LGS',
      requirement: { rank: 10, scope: 'SCHOOL' },
      iconName: 'medal',
      colorScheme: 'blue',
      points: 20,
      examType: ExamType.LGS,
    },

    // ==================== LGS DISTRICT/CITY RANKINGS ====================
    {
      name: 'İlçe Şampiyonu',
      description: 'LGS denemesinde ilçende 1. oldun',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_DISTRICT_1_LGS',
      requirement: { rank: 1, scope: 'DISTRICT' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 200,
      examType: ExamType.LGS,
    },
    {
      name: 'İlçede İlk 3',
      description: 'LGS denemesinde ilçende ilk 3\'e girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_DISTRICT_3_LGS',
      requirement: { rank: 3, scope: 'DISTRICT' },
      iconName: 'trophy',
      colorScheme: 'purple',
      points: 150,
      examType: ExamType.LGS,
    },
    {
      name: 'İlçede İlk 10',
      description: 'LGS denemesinde ilçende ilk 10\'a girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_DISTRICT_10_LGS',
      requirement: { rank: 10, scope: 'DISTRICT' },
      iconName: 'award',
      colorScheme: 'purple',
      points: 100,
      examType: ExamType.LGS,
    },
    {
      name: 'İl Şampiyonu',
      description: 'LGS denemesinde il genelinde 1. oldun',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_CITY_1_LGS',
      requirement: { rank: 1, scope: 'CITY' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 300,
      examType: ExamType.LGS,
    },
    {
      name: 'İlde İlk 10',
      description: 'LGS denemesinde il genelinde ilk 10\'a girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_CITY_10_LGS',
      requirement: { rank: 10, scope: 'CITY' },
      iconName: 'trophy',
      colorScheme: 'purple',
      points: 200,
      examType: ExamType.LGS,
    },
    {
      name: 'Türkiye İlk 100',
      description: 'LGS denemesinde Türkiye genelinde ilk 100\'e girdin',
      category: AchievementCategory.MILESTONE,
      type: 'RANK_GENERAL_100_LGS',
      requirement: { rank: 100, scope: 'GENERAL' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 500,
      examType: ExamType.LGS,
    },

    // ==================== LGS SCORE MILESTONES ====================
    {
      name: '300+ Puan',
      description: 'LGS denemesinde 300 puanı geçtin',
      category: AchievementCategory.MILESTONE,
      type: 'SCORE_300_LGS',
      requirement: { score: 300 },
      iconName: 'target',
      colorScheme: 'blue',
      points: 10,
      examType: ExamType.LGS,
    },
    {
      name: '350+ Puan',
      description: 'LGS denemesinde 350 puanı geçtin',
      category: AchievementCategory.MILESTONE,
      type: 'SCORE_350_LGS',
      requirement: { score: 350 },
      iconName: 'target',
      colorScheme: 'blue',
      points: 20,
      examType: ExamType.LGS,
    },
    {
      name: '400+ Puan',
      description: 'LGS denemesinde 400 puanı geçtin',
      category: AchievementCategory.MILESTONE,
      type: 'SCORE_400_LGS',
      requirement: { score: 400 },
      iconName: 'target',
      colorScheme: 'purple',
      points: 40,
      examType: ExamType.LGS,
    },
    {
      name: '450+ Puan',
      description: 'LGS denemesinde 450 puanı geçtin',
      category: AchievementCategory.MILESTONE,
      type: 'SCORE_450_LGS',
      requirement: { score: 450 },
      iconName: 'star',
      colorScheme: 'purple',
      points: 75,
      examType: ExamType.LGS,
    },
    {
      name: '480+ Puan',
      description: 'LGS denemesinde 480 puanı geçtin',
      category: AchievementCategory.MILESTONE,
      type: 'SCORE_480_LGS',
      requirement: { score: 480 },
      iconName: 'star',
      colorScheme: 'gold',
      points: 150,
      examType: ExamType.LGS,
    },
    {
      name: '500 Tam Puan',
      description: 'LGS denemesinde 500 tam puan aldın',
      category: AchievementCategory.MILESTONE,
      type: 'SCORE_500_LGS',
      requirement: { score: 500 },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 300,
      examType: ExamType.LGS,
    },

    // ==================== LGS PERFECT SCORES ====================
    {
      name: '90 Tam Puan',
      description: 'LGS denemesinde 90 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'PERFECT_90_LGS',
      requirement: { correct: 90, total: 90 },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 300,
      examType: ExamType.LGS,
    },
    {
      name: 'Sadece 1 Yanlış',
      description: 'LGS denemesinde sadece 1 yanlış yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'ALMOST_PERFECT_LGS',
      requirement: { wrong: 1, total: 90 },
      iconName: 'star',
      colorScheme: 'gold',
      points: 200,
      examType: ExamType.LGS,
    },
    {
      name: 'Sadece 2 Yanlış',
      description: 'LGS denemesinde sadece 2 yanlış yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'NEAR_PERFECT_LGS',
      requirement: { wrong: 2, total: 90 },
      iconName: 'star',
      colorScheme: 'purple',
      points: 150,
      examType: ExamType.LGS,
    },

    // ==================== LGS SUBJECT FULL SCORES ====================
    {
      name: 'Matematik Ustası (LGS)',
      description: 'LGS Matematik\'te 20 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_MATH_LGS',
      requirement: { subject: 'Matematik', correct: 20 },
      iconName: 'award',
      colorScheme: 'blue',
      points: 80,
      examType: ExamType.LGS,
    },
    {
      name: 'Türkçe Ustası (LGS)',
      description: 'LGS Türkçe\'de 20 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_TURKISH_LGS',
      requirement: { subject: 'Türkçe', correct: 20 },
      iconName: 'award',
      colorScheme: 'green',
      points: 80,
      examType: ExamType.LGS,
    },
    {
      name: 'Fen Bilimleri Ustası (LGS)',
      description: 'LGS Fen Bilimleri\'nde 20 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_SCIENCE_LGS',
      requirement: { subject: 'Fen Bilimleri', correct: 20 },
      iconName: 'award',
      colorScheme: 'purple',
      points: 80,
      examType: ExamType.LGS,
    },
    {
      name: 'T.C. İnkılap Tarihi Ustası (LGS)',
      description: 'LGS İnkılap Tarihi\'nde 10 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_HISTORY_LGS',
      requirement: { subject: 'T.C. İnkılap Tarihi', correct: 10 },
      iconName: 'award',
      colorScheme: 'red',
      points: 50,
      examType: ExamType.LGS,
    },
    {
      name: 'Din Kültürü Ustası (LGS)',
      description: 'LGS Din Kültürü\'nde 10 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_RELIGION_LGS',
      requirement: { subject: 'Din Kültürü', correct: 10 },
      iconName: 'award',
      colorScheme: 'yellow',
      points: 50,
      examType: ExamType.LGS,
    },
    {
      name: 'İngilizce Ustası (LGS)',
      description: 'LGS İngilizce\'de 10 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_ENGLISH_LGS',
      requirement: { subject: 'İngilizce', correct: 10 },
      iconName: 'award',
      colorScheme: 'blue',
      points: 50,
      examType: ExamType.LGS,
    },

    // ==================== TYT ACHIEVEMENTS ====================
    {
      name: 'TYT 120 Tam Puan',
      description: 'TYT\'de 120 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'PERFECT_TYT_120',
      requirement: { correct: 120, total: 120 },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 400,
      examType: ExamType.TYT,
    },
    {
      name: 'TYT Matematik Ustası',
      description: 'TYT Matematik\'te 40 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_MATH_TYT',
      requirement: { subject: 'Matematik', correct: 40 },
      iconName: 'award',
      colorScheme: 'blue',
      points: 120,
      examType: ExamType.TYT,
    },
    {
      name: 'TYT Türkçe Ustası',
      description: 'TYT Türkçe\'de 40 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_TURKISH_TYT',
      requirement: { subject: 'Türkçe', correct: 40 },
      iconName: 'award',
      colorScheme: 'green',
      points: 120,
      examType: ExamType.TYT,
    },
    {
      name: 'TYT Fen Ustası',
      description: 'TYT Fen Bilimleri\'nde 20 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_SCIENCE_TYT',
      requirement: { subject: 'Fen Bilimleri', correct: 20 },
      iconName: 'award',
      colorScheme: 'purple',
      points: 80,
      examType: ExamType.TYT,
    },
    {
      name: 'TYT Sosyal Ustası',
      description: 'TYT Sosyal Bilimler\'de 20 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_SOCIAL_TYT',
      requirement: { subject: 'Sosyal Bilimler', correct: 20 },
      iconName: 'award',
      colorScheme: 'orange',
      points: 80,
      examType: ExamType.TYT,
    },

    // ==================== AYT SAYISAL (MF) ====================
    {
      name: 'AYT Matematik Ustası (MF)',
      description: 'AYT Matematik\'te 40 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_MATH_AYT_MF',
      requirement: { subject: 'Matematik', correct: 40, field: 'MF' },
      iconName: 'award',
      colorScheme: 'blue',
      points: 150,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Fizik Ustası (MF)',
      description: 'AYT Fizik\'te 14 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_PHYSICS_AYT_MF',
      requirement: { subject: 'Fizik', correct: 14, field: 'MF' },
      iconName: 'award',
      colorScheme: 'purple',
      points: 80,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Kimya Ustası (MF)',
      description: 'AYT Kimya\'da 13 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_CHEMISTRY_AYT_MF',
      requirement: { subject: 'Kimya', correct: 13, field: 'MF' },
      iconName: 'award',
      colorScheme: 'green',
      points: 75,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Biyoloji Ustası (MF)',
      description: 'AYT Biyoloji\'de 13 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_BIOLOGY_AYT_MF',
      requirement: { subject: 'Biyoloji', correct: 13, field: 'MF' },
      iconName: 'award',
      colorScheme: 'green',
      points: 75,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Fen Ustası (MF)',
      description: 'AYT Fen Bilimleri\'nde 40 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_SCIENCE_AYT_MF',
      requirement: { subjects: ['Fizik', 'Kimya', 'Biyoloji'], correct: 40, field: 'MF' },
      iconName: 'trophy',
      colorScheme: 'purple',
      points: 200,
      examType: ExamType.AYT,
    },
    {
      name: 'Sayısal Şampiyonu (MF)',
      description: 'AYT Sayısal\'da 80 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'PERFECT_AYT_MF_80',
      requirement: { correct: 80, total: 80, field: 'MF' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 400,
      examType: ExamType.AYT,
    },

    // ==================== AYT SÖZEL (TS) ====================
    {
      name: 'AYT Edebiyat Ustası (TS)',
      description: 'AYT Edebiyat\'ta 24 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_LIT_AYT_TS',
      requirement: { subject: 'Edebiyat', correct: 24, field: 'TS' },
      iconName: 'award',
      colorScheme: 'green',
      points: 120,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Tarih-1 Ustası (TS)',
      description: 'AYT Tarih-1\'de 10 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_HIST1_AYT_TS',
      requirement: { subject: 'Tarih-1', correct: 10, field: 'TS' },
      iconName: 'award',
      colorScheme: 'red',
      points: 60,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Coğrafya-1 Ustası (TS)',
      description: 'AYT Coğrafya-1\'de 6 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_GEO1_AYT_TS',
      requirement: { subject: 'Coğrafya-1', correct: 6, field: 'TS' },
      iconName: 'award',
      colorScheme: 'blue',
      points: 50,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Tarih-2 Ustası (TS)',
      description: 'AYT Tarih-2\'de 11 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_HIST2_AYT_TS',
      requirement: { subject: 'Tarih-2', correct: 11, field: 'TS' },
      iconName: 'award',
      colorScheme: 'red',
      points: 65,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Coğrafya-2 Ustası (TS)',
      description: 'AYT Coğrafya-2\'de 11 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_GEO2_AYT_TS',
      requirement: { subject: 'Coğrafya-2', correct: 11, field: 'TS' },
      iconName: 'award',
      colorScheme: 'blue',
      points: 65,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Felsefe Ustası (TS)',
      description: 'AYT Felsefe Grubu\'nda 7 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_PHIL_AYT_TS',
      requirement: { subject: 'Felsefe', correct: 7, field: 'TS' },
      iconName: 'award',
      colorScheme: 'purple',
      points: 55,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Din Kültürü Ustası (TS)',
      description: 'AYT Din Kültürü\'nde 11 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_RELIGION_AYT_TS',
      requirement: { subject: 'Din Kültürü', correct: 11, field: 'TS' },
      iconName: 'award',
      colorScheme: 'yellow',
      points: 65,
      examType: ExamType.AYT,
    },
    {
      name: 'Sözel Şampiyonu (TS)',
      description: 'AYT Sözel testlerinde 120 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'PERFECT_AYT_TS_120',
      requirement: { correct: 120, total: 120, field: 'TS' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 400,
      examType: ExamType.AYT,
    },

    // ==================== AYT EŞİT AĞIRLIK (TM) ====================
    {
      name: 'Eşit Ağırlık Ustası (TM)',
      description: 'AYT Eşit Ağırlık testlerinde 96 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'PERFECT_AYT_TM_96',
      requirement: { correct: 96, total: 96, field: 'TM' },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 400,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Matematik Ustası (TM)',
      description: 'AYT Matematik\'te 40 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_MATH_AYT_TM',
      requirement: { subject: 'Matematik', correct: 40, field: 'TM' },
      iconName: 'award',
      colorScheme: 'blue',
      points: 150,
      examType: ExamType.AYT,
    },
    {
      name: 'AYT Edebiyat Ustası (TM)',
      description: 'AYT Edebiyat\'ta 24 sorunun hepsini doğru yaptın',
      category: AchievementCategory.MILESTONE,
      type: 'FULL_LIT_AYT_TM',
      requirement: { subject: 'Edebiyat', correct: 24, field: 'TM' },
      iconName: 'award',
      colorScheme: 'green',
      points: 120,
      examType: ExamType.AYT,
    },

    // ==================== CONSISTENCY ACHIEVEMENTS ====================
    {
      name: 'Sabırlı Öğrenci',
      description: '10 farklı deneme çözdün',
      category: AchievementCategory.CONSISTENCY,
      type: 'EXAMS_10',
      requirement: { examCount: 10 },
      iconName: 'book',
      colorScheme: 'blue',
      points: 30,
    },
    {
      name: 'Kararlı Öğrenci',
      description: '25 farklı deneme çözdün',
      category: AchievementCategory.CONSISTENCY,
      type: 'EXAMS_25',
      requirement: { examCount: 25 },
      iconName: 'book',
      colorScheme: 'purple',
      points: 75,
    },
    {
      name: 'Deneme Makinesi',
      description: '50 farklı deneme çözdün',
      category: AchievementCategory.CONSISTENCY,
      type: 'EXAMS_50',
      requirement: { examCount: 50 },
      iconName: 'book',
      colorScheme: 'gold',
      points: 150,
    },
    {
      name: 'Çalışkan Öğrenci',
      description: '100 saat çalışma tamamladın',
      category: AchievementCategory.CONSISTENCY,
      type: 'STUDY_100H',
      requirement: { hours: 100 },
      iconName: 'clock',
      colorScheme: 'blue',
      points: 50,
    },
    {
      name: 'Süper Çalışkan',
      description: '500 saat çalışma tamamladın',
      category: AchievementCategory.CONSISTENCY,
      type: 'STUDY_500H',
      requirement: { hours: 500 },
      iconName: 'clock',
      colorScheme: 'purple',
      points: 200,
    },
    {
      name: '1000 Soru Çözdün',
      description: 'Toplamda 1000 soru çözdün',
      category: AchievementCategory.CONSISTENCY,
      type: 'QUESTIONS_1000',
      requirement: { questions: 1000 },
      iconName: 'target',
      colorScheme: 'blue',
      points: 50,
    },
    {
      name: '5000 Soru Çözdün',
      description: 'Toplamda 5000 soru çözdün',
      category: AchievementCategory.CONSISTENCY,
      type: 'QUESTIONS_5000',
      requirement: { questions: 5000 },
      iconName: 'target',
      colorScheme: 'purple',
      points: 200,
    },
    {
      name: '10000 Soru Çözdün',
      description: 'Toplamda 10000 soru çözdün',
      category: AchievementCategory.CONSISTENCY,
      type: 'QUESTIONS_10000',
      requirement: { questions: 10000 },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 400,
    },

    // ==================== IMPROVEMENT ACHIEVEMENTS ====================
    {
      name: 'Hızlı Gelişim',
      description: 'Bir ayda net ortalamanı 10 artırdın',
      category: AchievementCategory.IMPROVEMENT,
      type: 'NET_IMPROVEMENT_10',
      requirement: { netIncrease: 10, period: 'month' },
      iconName: 'star',
      colorScheme: 'green',
      points: 50,
    },
    {
      name: 'Süper Gelişim',
      description: 'Bir ayda net ortalamanı 20 artırdın',
      category: AchievementCategory.IMPROVEMENT,
      type: 'NET_IMPROVEMENT_20',
      requirement: { netIncrease: 20, period: 'month' },
      iconName: 'star',
      colorScheme: 'purple',
      points: 100,
    },
    {
      name: 'Matematik Gelişimi',
      description: 'Matematik netini 5 artırdın',
      category: AchievementCategory.IMPROVEMENT,
      type: 'MATH_IMPROVEMENT_5',
      requirement: { subject: 'Matematik', netIncrease: 5 },
      iconName: 'star',
      colorScheme: 'blue',
      points: 30,
    },
    {
      name: 'Türkçe Gelişimi',
      description: 'Türkçe netini 5 artırdın',
      category: AchievementCategory.IMPROVEMENT,
      type: 'TURKISH_IMPROVEMENT_5',
      requirement: { subject: 'Türkçe', netIncrease: 5 },
      iconName: 'star',
      colorScheme: 'green',
      points: 30,
    },
    {
      name: 'Fen Gelişimi',
      description: 'Fen netini 5 artırdın',
      category: AchievementCategory.IMPROVEMENT,
      type: 'SCIENCE_IMPROVEMENT_5',
      requirement: { subject: 'Fen Bilimleri', netIncrease: 5 },
      iconName: 'star',
      colorScheme: 'purple',
      points: 30,
    },

    // ==================== GROUP ACHIEVEMENTS ====================
    {
      name: 'Takım Oyuncusu',
      description: 'Bir çalışma grubuna katıldın',
      category: AchievementCategory.GROUP,
      type: 'GROUP_MEMBER',
      requirement: { groupCount: 1 },
      iconName: 'award',
      colorScheme: 'blue',
      points: 10,
    },
    {
      name: 'Grup Lideri',
      description: 'Bir çalışma grubu oluşturdun',
      category: AchievementCategory.GROUP,
      type: 'GROUP_LEADER',
      requirement: { isLeader: true },
      iconName: 'crown',
      colorScheme: 'purple',
      points: 30,
    },
    {
      name: 'Popüler Öğrenci',
      description: '10 kişilik bir gruba liderlik ediyorsun',
      category: AchievementCategory.GROUP,
      type: 'GROUP_LEADER_10',
      requirement: { isLeader: true, memberCount: 10 },
      iconName: 'crown',
      colorScheme: 'gold',
      points: 50,
    },

    // ==================== SPECIAL ACHIEVEMENTS ====================
    {
      name: 'Sabah Kuşu',
      description: 'Sabah 6\'dan önce çalışmaya başladın',
      category: AchievementCategory.CONSISTENCY,
      type: 'EARLY_BIRD',
      requirement: { hour: 6, before: true },
      iconName: 'clock',
      colorScheme: 'orange',
      points: 20,
    },
    {
      name: 'Gece Kuşu',
      description: 'Gece 23\'ten sonra çalıştın',
      category: AchievementCategory.CONSISTENCY,
      type: 'NIGHT_OWL',
      requirement: { hour: 23, after: true },
      iconName: 'clock',
      colorScheme: 'purple',
      points: 20,
    },
    {
      name: 'Hafta Sonu Kahramanı',
      description: 'Hafta sonu tüm görevlerini tamamladın',
      category: AchievementCategory.STREAK,
      type: 'WEEKEND_WARRIOR',
      requirement: { weekend: true },
      iconName: 'flame',
      colorScheme: 'orange',
      points: 30,
    },
    {
      name: 'İlk Adım',
      description: 'İlk çalışma planını tamamladın',
      category: AchievementCategory.MILESTONE,
      type: 'FIRST_PLAN',
      requirement: { planCount: 1 },
      iconName: 'star',
      colorScheme: 'blue',
      points: 10,
    },
    {
      name: 'Deneme Savaşçısı',
      description: 'İlk denemeni tamamladın',
      category: AchievementCategory.MILESTONE,
      type: 'FIRST_EXAM',
      requirement: { examCount: 1 },
      iconName: 'trophy',
      colorScheme: 'blue',
      points: 10,
    },
  ];

  let created = 0;
  for (const achievement of achievements) {
    try {
      // Check if achievement with this type already exists for this school
      const existing = await prisma.achievement.findFirst({
        where: {
          schoolId,
          type: achievement.type,
        },
      });

      if (existing) {
        // Update existing
        await prisma.achievement.update({
          where: { id: existing.id },
          data: achievement,
        });
      } else {
        // Create new
        await prisma.achievement.create({
          data: {
            ...achievement,
            schoolId,
          },
        });
      }
      created++;
    } catch (error) {
      console.error(`Error creating achievement ${achievement.name}:`, error);
    }
  }

  console.log(`✅ Created/Updated ${created} achievements for school ${schoolId}`);
}
