import { AchievementCategory, ExamType, Prisma } from '@prisma/client';

export type AchievementSeedBundle = 'LGS' | 'TYT' | 'AYT' | 'CONSISTENCY';

export interface AchievementSeedDefinition {
  name: string;
  description: string;
  category: AchievementCategory;
  type: string;
  requirement: Prisma.InputJsonValue;
  iconName: string;
  colorScheme: string;
  points: number;
  examType?: ExamType;
}

const consistencyAchievements: AchievementSeedDefinition[] = [
  // Class rankings (general)
  {
    name: 'Sinif Sampiyonu',
    description: 'Denemede sinifinda 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_CLASS_1',
    requirement: { rank: 1, scope: 'CLASS' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 50,
  },
  {
    name: 'Sinifta Ilk 3',
    description: 'Denemede sinifinda ilk 3e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_CLASS_3',
    requirement: { rank: 3, scope: 'CLASS' },
    iconName: 'trophy',
    colorScheme: 'blue',
    points: 30,
  },
  {
    name: 'Sinifta Ilk 5',
    description: 'Denemede sinifinda ilk 5e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_CLASS_5',
    requirement: { rank: 5, scope: 'CLASS' },
    iconName: 'award',
    colorScheme: 'blue',
    points: 20,
  },
  {
    name: 'Sinifta Ilk 10',
    description: 'Denemede sinifinda ilk 10a girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_CLASS_10',
    requirement: { rank: 10, scope: 'CLASS' },
    iconName: 'medal',
    colorScheme: 'blue',
    points: 10,
  },

  // Streak
  {
    name: '1 Hafta Duzenli',
    description: '1 hafta boyunca gorevlerini aksatmadin',
    category: AchievementCategory.STREAK,
    type: 'STREAK_1W',
    requirement: { weeks: 1 },
    iconName: 'flame',
    colorScheme: 'orange',
    points: 10,
  },
  {
    name: '2 Hafta Duzenli',
    description: '2 hafta boyunca duzeni korudun',
    category: AchievementCategory.STREAK,
    type: 'STREAK_2W',
    requirement: { weeks: 2 },
    iconName: 'flame',
    colorScheme: 'orange',
    points: 25,
  },
  {
    name: '3 Hafta Duzenli',
    description: '3 hafta boyunca duzeni korudun',
    category: AchievementCategory.STREAK,
    type: 'STREAK_3W',
    requirement: { weeks: 3 },
    iconName: 'flame',
    colorScheme: 'orange',
    points: 50,
  },
  {
    name: '1 Ay Disiplin',
    description: '4 hafta boyunca duzeni korudun',
    category: AchievementCategory.STREAK,
    type: 'STREAK_4W',
    requirement: { weeks: 4 },
    iconName: 'flame',
    colorScheme: 'red',
    points: 80,
  },
  {
    name: '5 Hafta Disiplin',
    description: '5 hafta boyunca duzeni korudun',
    category: AchievementCategory.STREAK,
    type: 'STREAK_5W',
    requirement: { weeks: 5 },
    iconName: 'flame',
    colorScheme: 'red',
    points: 110,
  },
  {
    name: '8 Hafta Disiplin',
    description: '8 hafta boyunca duzeni korudun',
    category: AchievementCategory.STREAK,
    type: 'STREAK_8W',
    requirement: { weeks: 8 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 170,
  },
  {
    name: '3 Ay Kararlilik',
    description: '12 hafta boyunca duzeni korudun',
    category: AchievementCategory.STREAK,
    type: 'STREAK_12W',
    requirement: { weeks: 12 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 250,
  },

  // Consistency
  {
    name: 'Deneme Rutinine Giris',
    description: '10 deneme tamamladin',
    category: AchievementCategory.CONSISTENCY,
    type: 'CONSISTENCY_10_EXAMS',
    requirement: { examCount: 10 },
    iconName: 'book',
    colorScheme: 'blue',
    points: 30,
  },
  {
    name: 'Deneme Istikrari',
    description: '25 deneme tamamladin',
    category: AchievementCategory.CONSISTENCY,
    type: 'CONSISTENCY_25_EXAMS',
    requirement: { examCount: 25 },
    iconName: 'book',
    colorScheme: 'purple',
    points: 80,
  },
  {
    name: 'Deneme Makinesi',
    description: '50 deneme tamamladin',
    category: AchievementCategory.CONSISTENCY,
    type: 'CONSISTENCY_50_EXAMS',
    requirement: { examCount: 50 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 160,
  },
  {
    name: '100 Deneme Efsanesi',
    description: '100 deneme tamamladin',
    category: AchievementCategory.CONSISTENCY,
    type: 'CONSISTENCY_100_EXAMS',
    requirement: { examCount: 100 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 320,
  },
  {
    name: '100 Saat Calisma',
    description: 'Toplam 100 saat calisma yaptin',
    category: AchievementCategory.CONSISTENCY,
    type: 'STUDY_100H',
    requirement: { hours: 100 },
    iconName: 'clock',
    colorScheme: 'blue',
    points: 50,
  },
  {
    name: '250 Saat Calisma',
    description: 'Toplam 250 saat calisma yaptin',
    category: AchievementCategory.CONSISTENCY,
    type: 'STUDY_250H',
    requirement: { hours: 250 },
    iconName: 'clock',
    colorScheme: 'purple',
    points: 120,
  },
  {
    name: '500 Saat Calisma',
    description: 'Toplam 500 saat calisma yaptin',
    category: AchievementCategory.CONSISTENCY,
    type: 'STUDY_500H',
    requirement: { hours: 500 },
    iconName: 'clock',
    colorScheme: 'gold',
    points: 220,
  },
  {
    name: '1000 Saat Calisma',
    description: 'Toplam 1000 saat calisma yaptin',
    category: AchievementCategory.CONSISTENCY,
    type: 'STUDY_1000H',
    requirement: { hours: 1000 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 400,
  },
  {
    name: '1000 Soru Kulubu',
    description: 'Toplam 1000 soru cozdun',
    category: AchievementCategory.CONSISTENCY,
    type: 'QUESTIONS_1000',
    requirement: { questions: 1000 },
    iconName: 'target',
    colorScheme: 'blue',
    points: 50,
  },
  {
    name: '5000 Soru Kulubu',
    description: 'Toplam 5000 soru cozdun',
    category: AchievementCategory.CONSISTENCY,
    type: 'QUESTIONS_5000',
    requirement: { questions: 5000 },
    iconName: 'target',
    colorScheme: 'purple',
    points: 180,
  },
  {
    name: '10000 Soru Kulubu',
    description: 'Toplam 10000 soru cozdun',
    category: AchievementCategory.CONSISTENCY,
    type: 'QUESTIONS_10000',
    requirement: { questions: 10000 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 320,
  },
  {
    name: '25000 Soru Ustasi',
    description: 'Toplam 25000 soru cozdun',
    category: AchievementCategory.CONSISTENCY,
    type: 'QUESTIONS_25000',
    requirement: { questions: 25000 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 500,
  },

  // Improvement
  {
    name: 'Net Artisi +5',
    description: 'Bir ayda ortalama netini 5 arttirdin',
    category: AchievementCategory.IMPROVEMENT,
    type: 'NET_IMPROVEMENT_5',
    requirement: { netIncrease: 5, period: 'month' },
    iconName: 'star',
    colorScheme: 'green',
    points: 25,
  },
  {
    name: 'Net Artisi +10',
    description: 'Bir ayda ortalama netini 10 arttirdin',
    category: AchievementCategory.IMPROVEMENT,
    type: 'NET_IMPROVEMENT_10',
    requirement: { netIncrease: 10, period: 'month' },
    iconName: 'star',
    colorScheme: 'green',
    points: 60,
  },
  {
    name: 'Net Artisi +20',
    description: 'Bir ayda ortalama netini 20 arttirdin',
    category: AchievementCategory.IMPROVEMENT,
    type: 'NET_IMPROVEMENT_20',
    requirement: { netIncrease: 20, period: 'month' },
    iconName: 'star',
    colorScheme: 'purple',
    points: 130,
  },
  {
    name: 'Net Artisi +30',
    description: 'Bir ayda ortalama netini 30 arttirdin',
    category: AchievementCategory.IMPROVEMENT,
    type: 'NET_IMPROVEMENT_30',
    requirement: { netIncrease: 30, period: 'month' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 220,
  },
];

const lgsAchievements: AchievementSeedDefinition[] = [
  {
    name: 'Okulda Sampiyon (LGS)',
    description: 'LGS denemesinde okulunda 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_1_LGS',
    requirement: { rank: 1, scope: 'SCHOOL' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 100,
    examType: ExamType.LGS,
  },
  {
    name: 'Okulda Ilk 3 (LGS)',
    description: 'LGS denemesinde okulunda ilk 3e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_3_LGS',
    requirement: { rank: 3, scope: 'SCHOOL' },
    iconName: 'trophy',
    colorScheme: 'blue',
    points: 50,
    examType: ExamType.LGS,
  },
  {
    name: 'Okulda Ilk 5 (LGS)',
    description: 'LGS denemesinde okulunda ilk 5e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_5_LGS',
    requirement: { rank: 5, scope: 'SCHOOL' },
    iconName: 'award',
    colorScheme: 'blue',
    points: 30,
    examType: ExamType.LGS,
  },
  {
    name: 'Okulda Ilk 10 (LGS)',
    description: 'LGS denemesinde okulunda ilk 10a girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_10_LGS',
    requirement: { rank: 10, scope: 'SCHOOL' },
    iconName: 'medal',
    colorScheme: 'blue',
    points: 20,
    examType: ExamType.LGS,
  },
  {
    name: 'Ilcede Sampiyon (LGS)',
    description: 'LGS denemesinde ilcende 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_DISTRICT_1_LGS',
    requirement: { rank: 1, scope: 'DISTRICT' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 180,
    examType: ExamType.LGS,
  },
  {
    name: 'Ilcede Ilk 3 (LGS)',
    description: 'LGS denemesinde ilcende ilk 3e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_DISTRICT_3_LGS',
    requirement: { rank: 3, scope: 'DISTRICT' },
    iconName: 'trophy',
    colorScheme: 'purple',
    points: 130,
    examType: ExamType.LGS,
  },
  {
    name: 'Ilde Sampiyon (LGS)',
    description: 'LGS denemesinde ilde 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_CITY_1_LGS',
    requirement: { rank: 1, scope: 'CITY' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 260,
    examType: ExamType.LGS,
  },
  {
    name: 'Turkiye Ilk 100 (LGS)',
    description: 'LGS denemesinde Turkiye genelinde ilk 100e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_GENERAL_100_LGS',
    requirement: { rank: 100, scope: 'GENERAL' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 500,
    examType: ExamType.LGS,
  },

  {
    name: 'LGS 300+',
    description: 'LGS denemesinde 300 puani gectin',
    category: AchievementCategory.MILESTONE,
    type: 'SCORE_300_LGS',
    requirement: { score: 300 },
    iconName: 'target',
    colorScheme: 'blue',
    points: 10,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS 350+',
    description: 'LGS denemesinde 350 puani gectin',
    category: AchievementCategory.MILESTONE,
    type: 'SCORE_350_LGS',
    requirement: { score: 350 },
    iconName: 'target',
    colorScheme: 'blue',
    points: 20,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS 400+',
    description: 'LGS denemesinde 400 puani gectin',
    category: AchievementCategory.MILESTONE,
    type: 'SCORE_400_LGS',
    requirement: { score: 400 },
    iconName: 'target',
    colorScheme: 'purple',
    points: 40,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS 450+',
    description: 'LGS denemesinde 450 puani gectin',
    category: AchievementCategory.MILESTONE,
    type: 'SCORE_450_LGS',
    requirement: { score: 450 },
    iconName: 'star',
    colorScheme: 'purple',
    points: 75,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS 480+',
    description: 'LGS denemesinde 480 puani gectin',
    category: AchievementCategory.MILESTONE,
    type: 'SCORE_480_LGS',
    requirement: { score: 480 },
    iconName: 'star',
    colorScheme: 'gold',
    points: 150,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS 500 Tam Puan',
    description: 'LGS denemesinde 500 tam puan aldin',
    category: AchievementCategory.MILESTONE,
    type: 'SCORE_500_LGS',
    requirement: { score: 500 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 300,
    examType: ExamType.LGS,
  },

  {
    name: 'LGS Kusursuz',
    description: 'LGS denemesinde kusursuz performans',
    category: AchievementCategory.MILESTONE,
    type: 'PERFECT_LGS',
    requirement: { totalCorrect: 90 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 320,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS Neredeyse Kusursuz I',
    description: 'LGS denemesinde 1 net farkla kusursuzu kacirdin',
    category: AchievementCategory.MILESTONE,
    type: 'NEAR_PERFECT_1_LGS',
    requirement: { totalNet: 89 },
    iconName: 'star',
    colorScheme: 'gold',
    points: 220,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS Neredeyse Kusursuz II',
    description: 'LGS denemesinde 2 net farkla kusursuzu kacirdin',
    category: AchievementCategory.MILESTONE,
    type: 'NEAR_PERFECT_2_LGS',
    requirement: { totalNet: 88 },
    iconName: 'star',
    colorScheme: 'purple',
    points: 170,
    examType: ExamType.LGS,
  },

  // Motivational extras
  {
    name: 'LGS Son Viraj',
    description: 'LGS hedefi icin son 30 gun disiplinli calisma',
    category: AchievementCategory.CONSISTENCY,
    type: 'LGS_FINAL_SPRINT_30D',
    requirement: { streakDays: 30, goal: 'LGS' },
    iconName: 'flame',
    colorScheme: 'red',
    points: 140,
    examType: ExamType.LGS,
  },
  {
    name: 'LGS Net Patlamasi',
    description: 'LGS net ortalamasinda bir ayda +15 artis',
    category: AchievementCategory.IMPROVEMENT,
    type: 'LGS_NET_BOOST_15',
    requirement: { netIncrease: 15, period: 'month' },
    iconName: 'target',
    colorScheme: 'green',
    points: 110,
    examType: ExamType.LGS,
  },
];

const tytAchievements: AchievementSeedDefinition[] = [
  {
    name: 'Okulda Sampiyon (TYT)',
    description: 'TYT denemesinde okulunda 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_1_TYT',
    requirement: { rank: 1, scope: 'SCHOOL' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 90,
    examType: ExamType.TYT,
  },
  {
    name: 'Okulda Ilk 3 (TYT)',
    description: 'TYT denemesinde okulunda ilk 3e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_3_TYT',
    requirement: { rank: 3, scope: 'SCHOOL' },
    iconName: 'trophy',
    colorScheme: 'blue',
    points: 55,
    examType: ExamType.TYT,
  },
  {
    name: 'Okulda Ilk 5 (TYT)',
    description: 'TYT denemesinde okulunda ilk 5e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_5_TYT',
    requirement: { rank: 5, scope: 'SCHOOL' },
    iconName: 'award',
    colorScheme: 'blue',
    points: 35,
    examType: ExamType.TYT,
  },
  {
    name: 'Okulda Ilk 10 (TYT)',
    description: 'TYT denemesinde okulunda ilk 10a girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_10_TYT',
    requirement: { rank: 10, scope: 'SCHOOL' },
    iconName: 'medal',
    colorScheme: 'blue',
    points: 25,
    examType: ExamType.TYT,
  },
  {
    name: 'Ilcede Sampiyon (TYT)',
    description: 'TYT denemesinde ilcende 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_DISTRICT_1_TYT',
    requirement: { rank: 1, scope: 'DISTRICT' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 170,
    examType: ExamType.TYT,
  },
  {
    name: 'Ilde Sampiyon (TYT)',
    description: 'TYT denemesinde ilde 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_CITY_1_TYT',
    requirement: { rank: 1, scope: 'CITY' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 250,
    examType: ExamType.TYT,
  },
  {
    name: 'TYT 120 Tam',
    description: 'TYTde 120 sorunun hepsini dogru yaptin',
    category: AchievementCategory.MILESTONE,
    type: 'PERFECT_TYT_120',
    requirement: { correct: 120, total: 120 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 400,
    examType: ExamType.TYT,
  },
  {
    name: 'TYT Matematik Ustasi',
    description: 'TYT Matematikte 40 sorunun hepsini dogru yaptin',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_MATH_TYT',
    requirement: { subject: 'Matematik', correct: 40 },
    iconName: 'award',
    colorScheme: 'blue',
    points: 120,
    examType: ExamType.TYT,
  },
  {
    name: 'TYT Turkce Ustasi',
    description: 'TYT Turkcede 40 sorunun hepsini dogru yaptin',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_TURKISH_TYT',
    requirement: { subject: 'Turkce', correct: 40 },
    iconName: 'award',
    colorScheme: 'green',
    points: 120,
    examType: ExamType.TYT,
  },
  {
    name: 'TYT Fen Ustasi',
    description: 'TYT Fende 20 sorunun hepsini dogru yaptin',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_SCIENCE_TYT',
    requirement: { subject: 'Fen Bilimleri', correct: 20 },
    iconName: 'award',
    colorScheme: 'purple',
    points: 90,
    examType: ExamType.TYT,
  },
  {
    name: 'TYT Sosyal Ustasi',
    description: 'TYT Sosyalde 20 sorunun hepsini dogru yaptin',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_SOCIAL_TYT',
    requirement: { subject: 'Sosyal Bilimler', correct: 20 },
    iconName: 'award',
    colorScheme: 'orange',
    points: 90,
    examType: ExamType.TYT,
  },
  // Motivational extras
  {
    name: 'TYT Momentum 5',
    description: 'Art arda 5 TYT denemesinde hedef netini tutturdun',
    category: AchievementCategory.CONSISTENCY,
    type: 'TYT_MOMENTUM_5',
    requirement: { consecutiveExams: 5, examType: 'TYT' },
    iconName: 'flame',
    colorScheme: 'red',
    points: 90,
    examType: ExamType.TYT,
  },
  {
    name: 'TYT Net +10',
    description: 'Bir ayda TYT ortalama netinde +10 artis',
    category: AchievementCategory.IMPROVEMENT,
    type: 'TYT_NET_BOOST_10',
    requirement: { netIncrease: 10, period: 'month' },
    iconName: 'target',
    colorScheme: 'green',
    points: 95,
    examType: ExamType.TYT,
  },
  {
    name: 'TYT Son 60 Gun',
    description: 'TYT hedefin icin son 60 gunde istikrar',
    category: AchievementCategory.CONSISTENCY,
    type: 'TYT_FINAL_60D',
    requirement: { streakDays: 60, goal: 'TYT' },
    iconName: 'clock',
    colorScheme: 'purple',
    points: 160,
    examType: ExamType.TYT,
  },
];

const aytAchievements: AchievementSeedDefinition[] = [
  {
    name: 'Okulda Sampiyon (AYT)',
    description: 'AYT denemesinde okulunda 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_1_AYT',
    requirement: { rank: 1, scope: 'SCHOOL' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 100,
    examType: ExamType.AYT,
  },
  {
    name: 'Okulda Ilk 3 (AYT)',
    description: 'AYT denemesinde okulunda ilk 3e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_3_AYT',
    requirement: { rank: 3, scope: 'SCHOOL' },
    iconName: 'trophy',
    colorScheme: 'blue',
    points: 60,
    examType: ExamType.AYT,
  },
  {
    name: 'Okulda Ilk 5 (AYT)',
    description: 'AYT denemesinde okulunda ilk 5e girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_5_AYT',
    requirement: { rank: 5, scope: 'SCHOOL' },
    iconName: 'award',
    colorScheme: 'blue',
    points: 40,
    examType: ExamType.AYT,
  },
  {
    name: 'Okulda Ilk 10 (AYT)',
    description: 'AYT denemesinde okulunda ilk 10a girdin',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_SCHOOL_10_AYT',
    requirement: { rank: 10, scope: 'SCHOOL' },
    iconName: 'medal',
    colorScheme: 'blue',
    points: 30,
    examType: ExamType.AYT,
  },
  {
    name: 'Ilcede Sampiyon (AYT)',
    description: 'AYT denemesinde ilcende 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_DISTRICT_1_AYT',
    requirement: { rank: 1, scope: 'DISTRICT' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 180,
    examType: ExamType.AYT,
  },
  {
    name: 'Ilde Sampiyon (AYT)',
    description: 'AYT denemesinde ilde 1. oldun',
    category: AchievementCategory.MILESTONE,
    type: 'RANK_CITY_1_AYT',
    requirement: { rank: 1, scope: 'CITY' },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 260,
    examType: ExamType.AYT,
  },
  {
    name: 'Sayisal Sampiyonu (MF)',
    description: 'AYT MF testlerinde 80de 80',
    category: AchievementCategory.MILESTONE,
    type: 'PERFECT_AYT_MF_80',
    requirement: { field: 'MF', correct: 80, total: 80 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 420,
    examType: ExamType.AYT,
  },
  {
    name: 'Sozel Sampiyonu (TS)',
    description: 'AYT TS testlerinde 120de 120',
    category: AchievementCategory.MILESTONE,
    type: 'PERFECT_AYT_TS_120',
    requirement: { field: 'TS', correct: 120, total: 120 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 420,
    examType: ExamType.AYT,
  },
  {
    name: 'EA Sampiyonu (TM)',
    description: 'AYT TM testlerinde 96da 96',
    category: AchievementCategory.MILESTONE,
    type: 'PERFECT_AYT_TM_96',
    requirement: { field: 'TM', correct: 96, total: 96 },
    iconName: 'crown',
    colorScheme: 'gold',
    points: 420,
    examType: ExamType.AYT,
  },
  {
    name: 'AYT Matematik Ustasi (MF)',
    description: 'AYT Matematikte 40ta 40',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_MATH_AYT_MF',
    requirement: { field: 'MF', subject: 'Matematik', correct: 40 },
    iconName: 'award',
    colorScheme: 'blue',
    points: 150,
    examType: ExamType.AYT,
  },
  {
    name: 'AYT Fen Ustasi (MF)',
    description: 'AYT Fende 40ta 40',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_SCIENCE_AYT_MF',
    requirement: { field: 'MF', subjects: ['Fizik', 'Kimya', 'Biyoloji'], correct: 40 },
    iconName: 'award',
    colorScheme: 'purple',
    points: 180,
    examType: ExamType.AYT,
  },
  {
    name: 'AYT Edebiyat Ustasi (TS)',
    description: 'AYT Edebiyatta 24te 24',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_LIT_AYT_TS',
    requirement: { field: 'TS', subject: 'Edebiyat', correct: 24 },
    iconName: 'award',
    colorScheme: 'green',
    points: 120,
    examType: ExamType.AYT,
  },
  {
    name: 'AYT Matematik Ustasi (TM)',
    description: 'AYT Matematikte 40ta 40',
    category: AchievementCategory.MILESTONE,
    type: 'FULL_MATH_AYT_TM',
    requirement: { field: 'TM', subject: 'Matematik', correct: 40 },
    iconName: 'award',
    colorScheme: 'blue',
    points: 140,
    examType: ExamType.AYT,
  },
  // Motivational extras
  {
    name: 'AYT Son Sprint 45',
    description: 'AYT hedefin icin son 45 gunde istikrar',
    category: AchievementCategory.CONSISTENCY,
    type: 'AYT_FINAL_SPRINT_45D',
    requirement: { streakDays: 45, goal: 'AYT' },
    iconName: 'flame',
    colorScheme: 'red',
    points: 170,
    examType: ExamType.AYT,
  },
  {
    name: 'AYT Net +8',
    description: 'Bir ayda AYT ortalama netinde +8 artis',
    category: AchievementCategory.IMPROVEMENT,
    type: 'AYT_NET_BOOST_8',
    requirement: { netIncrease: 8, period: 'month' },
    iconName: 'target',
    colorScheme: 'green',
    points: 105,
    examType: ExamType.AYT,
  },
  {
    name: 'AYT Planina Sadik',
    description: '4 hafta boyunca AYT planina %90 uyum',
    category: AchievementCategory.CONSISTENCY,
    type: 'AYT_PLAN_COMPLIANCE_4W',
    requirement: { planComplianceRate: 90, weeks: 4 },
    iconName: 'clock',
    colorScheme: 'purple',
    points: 125,
    examType: ExamType.AYT,
  },
];

export const ACHIEVEMENT_SEED_BUNDLES: Record<
  AchievementSeedBundle,
  AchievementSeedDefinition[]
> = {
  LGS: lgsAchievements,
  TYT: tytAchievements,
  AYT: aytAchievements,
  CONSISTENCY: consistencyAchievements,
};

export const ALL_ACHIEVEMENT_BUNDLES: AchievementSeedBundle[] = [
  'LGS',
  'TYT',
  'AYT',
  'CONSISTENCY',
];

export function getBundleAchievements(bundle: AchievementSeedBundle) {
  return ACHIEVEMENT_SEED_BUNDLES[bundle];
}

export function getAchievementsForBundles(bundles: AchievementSeedBundle[]) {
  return bundles.flatMap((bundle) => ACHIEVEMENT_SEED_BUNDLES[bundle]);
}
